### ISSUE TITLE
[New Feature]: Adding a great gradient or image in the background

### ISSUE THREAD

**Issue by Rakshit-gen** [GameSphere-MultiPlayer/Squard-line#16]
### 🎮 feature Request

Add the gradient to make the background of the UI look much better.

### Point down the features

1. Adding a great gradient

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me, I have experience in designing

**Comment by Durgesh4993** [comment]
@Rakshit-gen @Anou25 Please raise any other issue, someone is already working on ui

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
