### ISSUE TITLE
[Bug]: Responsiveness 

### ISSUE THREAD

**Issue by callmeVAMP** [GameSphere-MultiPlayer/Squard-line#22]
### Give a brief about the bug ✍️

Description icons can be made better with user friendly experience. Text can be made more appealing. Game rules can be explained in beginning.

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by chaanakyaaM** [comment]
I would like to make the website more responsive and interactive.
would you kindly assign me to this issue ???

**Comment by Durgesh4993** [comment]
@callmeVAMP @chaanakyaaM Please raise any other issue, someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
