### ISSUE TITLE
[Enhancement]:  NOT APPELING

### ISSUE THREAD

**Issue by SadiyaTahsin29** [GameSphere-MultiPlayer/Squard-line#25]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement the game need a little improvement

### Describe the solution you'd like

Solution steps add more graphic and also  need some sound ,to make it interesting add timer

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@SadiyaTahsin29 Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by SadiyaTahsin29** [comment]
I would like to make the starting more interesting as well as ,I would like to add few instruction to how  the game work
