### ISSUE TITLE
[Enhancement]: home UI

### ISSUE THREAD

**Issue by Vipullakum007** [GameSphere-MultiPlayer/Squard-line#28]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement : home UI very difficult to understand at first time. either add how to use button / how to play button or make UI easy to understand. 

### Describe the solution you'd like

Solution steps : either add how to use button / how to play button or make UI easy to understand.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Vipullakum007 Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
