### ISSUE TITLE
[Bug]: lack of responsiveness

### ISSUE THREAD

**Issue by Vipullakum007** [GameSphere-MultiPlayer/Squard-line#29]
### Give a brief about the bug ✍️

Description : game is not responsive make it responsive

### What is the expected behavior? 🤔

Description : it should be responsive

### Provide step by step information reproduce the bug 📄

Description : use media query to make it responsive

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@Vipullakum007 Please raise any other issue, someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
