### ISSUE TITLE
[Question]:  Add code of conduct

### ISSUE THREAD

**Issue by hasmithagunda123** [GameSphere-MultiPlayer/Squard-line#32]
\
I want to add code of conduct assign me

**Comment by Vaibhavtech2006** [comment]
i want to add code of conduct assign me

**Comment by Durgesh4993** [comment]
@hasmithagunda123 @Vaibhavtech2006 we already have code of conduct file Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by hasmithagunda123** [comment]
Assign me some other work . I want to contribute your project. Please assign me some issue
