### ISSUE TITLE
[Enhancement]: Our current scoreboard's layout makes it a bit challenging for players to quickly grasp their score. I propose a redesign that prioritizes clarity and readability, enhancing the overall user experience.

### ISSUE THREAD

**Issue by Aanya10Mishra** [GameSphere-MultiPlayer/Squard-line#35]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement

### Describe the solution you'd like

Solution steps: I will use the js library like anime.js .

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Aanya10Mishra** [comment]
Hi @Durgesh4993 ,

I'm Aanya Mishra, a GSSoC participant excited to contribute to Squared-line. I came across this issue and believe my skills in Frontend align well. I'm eager to learn and contribute meaningfully. Would you consider assigning it to me?

**Comment by Durgesh4993** [comment]
@Aanya10Mishra Please raise any other issue, i'll assign you...

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
