### ISSUE TITLE
[New Feature]: Leaderboard and Login Page

### ISSUE THREAD

**Issue by aravindhbalaji04** [GameSphere-MultiPlayer/Squard-line#4]
### 🎮 feature Request

We can add a leaderboard to the game by asking them their name after completing each levels, and then update their points if their name already exists and then, we could also make a login page for this game.

### Point down the features

1. Login Page
2. Leaderboard with names and their respective points in display

### Select program in which you are contributing

GSSoC '24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by surendar-05** [comment]
Hey!! Assign this issue to me i want to work on this?under Gssoc'24
