### ISSUE TITLE
[New Feature]: High Score Tracking

### ISSUE THREAD

**Issue by hasmithagunda123** [GameSphere-MultiPlayer/Squard-line#43]
### 🎮 feature Request

Optionally, implement a high score feature to keep track of the player's best performances. Display the highest score achieved by the player either on the game screen or in a separate high score table.

### Point down the features

assign me under gssoc

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SanaAzeem512** [comment]
please assign this issue to me under GSSOC24

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
