### ISSUE TITLE
[Enhancement]: Confirmation for restart 

### ISSUE THREAD

**Issue by sharmi4590** [GameSphere-MultiPlayer/Squard-line#45]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

The user should be asked first wheather the game really has to be restarted or not because sometimes we can click the R button bymistake and the whole levels will be gone.
(The game should not end like this 🙃)

### Describe the solution you'd like

For this I will add a pop up alert box which will appear on clicking the R button asking the user whether they really want to end the game and alert them that they will be redirecting to level one . The pop up will have yes or no if test them restart , if not game continues. 
Also we can add a back button below which redirects to the first home page if any wants to read the instruction again.
I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by KhushiSahu0108** [comment]
Please assign this  issue to me.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
