### ISSUE TITLE
[New Feature]: Add heading to the game 

### ISSUE THREAD

**Issue by Jyoti040** [GameSphere-MultiPlayer/Squard-line#46]
### 🎮 feature Request

There is no heading to the game . I want to add the it to enhance the UI of the page.

### Point down the features

feature points:-
this is enhance the UI of page 

### Select program in which you are contributing

GSSOC 24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by roushanverma23** [comment]
@Durgesh4993 please assign this task, I want to work on this

![contributor badge 2024](https://github.com/The-MindSpace/MindSpace-Web/assets/137530796/1ce1358a-c200-4da1-9750-2212b2a1c26d)

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
