### ISSUE TITLE
Add scorecard rather than the alert message.

### ISSUE THREAD

**Issue by Riddhi162** [GameSphere-MultiPlayer/Squard-line#49]
### 🎮 feature Request

It describes the score of the user and also there will be a share button with which user can share his/her score accross various platform.

### Point down the features

As sson as the score card will open there will be confetti burst animation.
Then on score card name of user , his/her score , a punch line,and play more option or play again option will be there,also share button to share the scorecard across various platform.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
