### ISSUE TITLE
[New Feature]:  Change font

### ISSUE THREAD

**Issue by Ridhima10** [GameSphere-MultiPlayer/Squard-line#52]
### 🎮 feature Request

I would like to change the font

### Point down the features

Since it is a game, i would like to change the font which matches the font of website

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Tarungupta18** [comment]
assign me

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
