### ISSUE TITLE
Adding Day and Night mode, and Improving the UI [New Feature]: 

### ISSUE THREAD

**Issue by Dhruv-Gaba** [GameSphere-MultiPlayer/Squard-line#54]
### Description
Incorporating light and dark mode in the game for improving user experience and improving the UI for making it more user appealing.

![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/141745373/6293a252-3b20-4f92-9502-b23843ff5aef)

### Features
- User will be able to switch between the bright light theme and the dark theme, enhancing the user experience.
- Designing a better UI for the web application will make it look more appealing to the users.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by nitish9966** [comment]
@Dhruv-Gaba I'm a GSSoC Contributor. And I would like to solve this issue and please assign this issue and I follow Contributing Guideline of this project

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
