### ISSUE TITLE
colour gradient , landing page ,game over and next level shoul be good page 

### ISSUE THREAD

**Issue by ekramzafar** [GameSphere-MultiPlayer/Squard-line#56]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

 in this game enhance colour of box and change background .when we start it it should be landing page . game over system and it's game over declear when time extend or wrong sq. chosen next level.

### Describe the solution you'd like

Solution stepsmake css file of colour gradient of sq. and background colour should be there  it have to be first landing page .it should have game over declaration 

please get in GSSoC24

### Select program in which you are contributing

GSSoC23, Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
