### ISSUE TITLE
[New Feature]: Adding an appealing background for better UI/UX.

### ISSUE THREAD

**Issue by Siddhant-Mahato** [GameSphere-MultiPlayer/Squard-line#58]
### 🎮 feature Request

Feature  : 

I want to contribute by adding an appealing gradient background so be more good for UI/UX.

Screenshots :

![Screenshot (639)](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/127202564/0e434615-ee53-42ea-a642-91c4a76a5d1c)

Likewise will add more appealing UI

### Point down the features

feature points : 

1. Appealing UI/UX

2. Better View

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Siddhant-Mahato** [comment]
Hello PA, 

Can you please assign me this task ?

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
