### ISSUE TITLE
[Enhancement]: Better Instructions screen.

### ISSUE THREAD

**Issue by VijaySamant4368** [GameSphere-MultiPlayer/Squard-line#63]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Currently the Instructions screen has basic grammatical error (The first word after full-stop/period being lower-cased), as can be seen in the following screenshot of the game:

![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/145102345/72d1e086-bf4d-410f-a57e-23eb5c060560)
 

### Describe the solution you'd like

I will make sure that the instructions are written in Sentence Case

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anjankumarkamalapur** [comment]
Hi, I would like to work on this issue , and solve it by adding clear instructions where all age people can understand, could you please assign this to me.
