### ISSUE TITLE
[Enhancement]: Addition of a Dedicated Play Button in Squared Game.

### ISSUE THREAD

**Issue by tanya-54** [GameSphere-MultiPlayer/Squard-line#68]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The current implementation of the Squared Game includes a "Tap to Play" text that changes color, prompting users to start the game. However, there is no specific button for playing. Adding a dedicated play button would enhance usability and improve the overall user experience by providing a clearer and more intuitive interface.

Description:
In the Squared Game, the "Tap to Play" text serves as the interactive element to start the game. While this text changes color to indicate interactivity, the absence of a specific play button can be confusing for users, especially those who might expect a more conventional interface element like a button. A dedicated play button would make the action more obvious, reduce ambiguity, and provide a more intuitive interaction point for users.

Steps to Reproduce:
Open the Squared Game interface.
Observe the "Tap to Play" text that changes color when hovered over or tapped.
Note the absence of a specific play button, which may lead to confusion about how to start the game.
Expected Behavior:
There should be a dedicated play button that clearly indicates the action to start the game. This button should have a recognizable design, such as a "Play" label or an icon, making it immediately apparent to users how to begin playing.

Current Behavior:
The game currently uses a "Tap to Play" text that changes color to indicate interactivity, but lacks a specific button for playing, which can be less intuitive and potentially confusing for some users.

### Describe the solution you'd like

Solution steps
1. Identify the Current Implementation.
2. Design the Play Button
3. Update the HTML Structure
4. Style the Play Button with CSS
Include styles for different states of the button, such as normal, hover, and active states, to provide visual feedback to users.
5. Bind the Button with JavaScript
Update or write JavaScript to link the play button to the game's start functionality.
Ensure that clicking the play button triggers the existing game-start logic.
6. Test the Implementation.
7. Adjust Existing "Tap to Play" Text

program in which contributing is Gssoc'24.

this can be the steps ....

please assign me this issue as a contributor i would love to decorate the game for good  user experience.

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
