### ISSUE TITLE
[Enhancement]: Text and UI is complicated to understand.

### ISSUE THREAD

**Issue by zeeno2616** [GameSphere-MultiPlayer/Squard-line#7]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement:
The instructions provided for the game are hard to understand.
The time/score board is also complex for normal understanding.

### Describe the solution you'd like

Editing the instructions and the UI around it to make it easier to understand and to make the user experience better.
Make changes to the scoreboard to show the score in a more easy to understand way. Similarly for the clock, add a digital/analog clock feature instead.

Please assign this to me under the GSSoC'24 program.

### Select program in which you are contributing

Other

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by r7projects-shayan** [comment]
Hey @Durgesh4993, I'm Shayan a full stack developer. I love the game so much and I want to change the UI to a more user friendly version. I'll start working as soon as you assign me this project issue.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@zeeno2616 Sir, Please assign this issue to me

**Comment by Durgesh4993** [comment]
@zeeno2616 @cpratik1307 @r7projects-shayan Please raise any other issue, because someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
