### ISSUE TITLE
[Enhancement]: footer

### ISSUE THREAD

**Issue by Jagpreet153** [GameSphere-MultiPlayer/Squard-line#73]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Adding a footer in the game 

### Describe the solution you'd like

I will be adding a responsive footer with social media links

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by jayanththalla** [comment]
please assign me @pa

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)

**Comment by heli0707** [comment]
I would like to work on this please assign it to me
