### ISSUE TITLE
[Enhancement]:add favicon to the page

### ISSUE THREAD

**Issue by jayanththalla** [GameSphere-MultiPlayer/Squard-line#74]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
The title page looks dull. Add a favicon to the page.

### Describe the solution you'd like

Solution steps
By adding a favicon beside the squad-line.
please assign me @pa

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
