### ISSUE TITLE
Adding game Rules instead of empty space

### ISSUE THREAD

**Issue by Dhruv-Gaba** [GameSphere-MultiPlayer/Squard-line#76]
### Description
Instead of the empty space present on the sides of the game we can add the rules on 'how to play the game'. This would help the users to understand how to play the game and will improve the user experience.

![image](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/141745373/b582bd0b-4b9e-4487-a583-75c371a29101)

### Point down the features

Adding Game rules in the empty space on the sides of the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you....
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
